interface Lesson {
  class: number;
  subject: string;
  topic: string;
}

export const lessons: Lesson[] = [
  { class: 8, subject: "Science", topic: "Force and Pressure" },
  { class: 8, subject: "Science", topic: "Friction" },
  { class: 8, subject: "Science", topic: "Sound" },
  {
    class: 8,
    subject: "Science",
    topic: "Chemical Effects of Electric Current",
  },
  { class: 8, subject: "Science", topic: "Light" },
  { class: 8, subject: "Mathematics", topic: "Rational Numbers" },
  {
    class: 8,
    subject: "Mathematics",
    topic: "Linear Equations in One Variable",
  },
  { class: 8, subject: "Mathematics", topic: "Squares and Square Roots" },
  { class: 8, subject: "Mathematics", topic: "Cubes and Cube Roots" },
  {
    class: 8,
    subject: "Mathematics",
    topic: "Algebraic Expressions and Identities",
  },
  { class: 8, subject: "Mathematics", topic: "Factorization" },
  { class: 9, subject: "Science", topic: "Matter in Our Surroundings" },
  { class: 9, subject: "Science", topic: "Is Matter Around Us Pure" },
  { class: 9, subject: "Science", topic: "Atoms and Molecules" },
  { class: 9, subject: "Science", topic: "Structure of the Atom" },
  { class: 9, subject: "Science", topic: "Motion" },
  { class: 9, subject: "Science", topic: "Force and Laws of Motion" },
  { class: 9, subject: "Science", topic: "Gravitation" },
  { class: 9, subject: "Science", topic: "Work and Energy" },
  { class: 9, subject: "Science", topic: "Sound" },
  { class: 9, subject: "Mathematics", topic: "Polynomials" },
  {
    class: 9,
    subject: "Mathematics",
    topic: "Linear Equations in Two Variables",
  },
  { class: 9, subject: "Mathematics", topic: "Coordinate Geometry" },
  { class: 9, subject: "Mathematics", topic: "Probability" },
  { class: 10, subject: "Science", topic: "Chemical Reactions and Equations" },
  { class: 10, subject: "Science", topic: "Acids, Bases, and Salts" },
  { class: 10, subject: "Science", topic: "Metals and Non-metals" },
  { class: 10, subject: "Science", topic: "Carbon and its Compounds" },
  {
    class: 10,
    subject: "Science",
    topic: "Periodic Classification of Elements",
  },
  { class: 10, subject: "Science", topic: "How do Organisms Reproduce?" },
  { class: 10, subject: "Science", topic: "Heredity and Evolution" },
  { class: 10, subject: "Science", topic: "Light – Reflection and Refraction" },
  { class: 10, subject: "Science", topic: "Electricity" },
  {
    class: 10,
    subject: "Science",
    topic: "Magnetic Effects of Electric Current",
  },
  { class: 10, subject: "Mathematics", topic: "Polynomials" },
  {
    class: 10,
    subject: "Mathematics",
    topic: "Pair of Linear Equations in Two Variables",
  },
  { class: 10, subject: "Mathematics", topic: "Quadratic Equations" },
  { class: 10, subject: "Mathematics", topic: "Introduction to Trigonometry" },
  {
    class: 10,
    subject: "Mathematics",
    topic: "Some Applications of Trigonometry",
  },
  { class: 10, subject: "Mathematics", topic: "Probability" },
  { class: 11, subject: "Physics", topic: "Kinematics" },
  { class: 11, subject: "Physics", topic: "Laws of Motion" },
  { class: 11, subject: "Physics", topic: "Work, Energy, and Power" },
  { class: 11, subject: "Physics", topic: "Rotational Motion" },
  { class: 11, subject: "Physics", topic: "Thermodynamics" },
  { class: 11, subject: "Physics", topic: "Oscillations and Waves" },
  { class: 11, subject: "Physics", topic: "Properties of Bulk Matter" },
  {
    class: 11,
    subject: "Chemistry",
    topic: "Some Basic Concepts of Chemistry",
  },
  { class: 11, subject: "Chemistry", topic: "Structure of Atom" },
  {
    class: 11,
    subject: "Chemistry",
    topic: "Chemical Bonding and Molecular Structure",
  },
  { class: 11, subject: "Chemistry", topic: "Equilibrium" },
  { class: 11, subject: "Chemistry", topic: "Redox Reactions" },
  { class: 11, subject: "Chemistry", topic: "The s-Block Elements" },
  {
    class: 11,
    subject: "Chemistry",
    topic: "Organic Chemistry - Some Basic Principles and Techniques",
  },
  { class: 11, subject: "Chemistry", topic: "Hydrocarbons" },
  { class: 11, subject: "Mathematics", topic: "Sets" },
  { class: 11, subject: "Mathematics", topic: "Trigonometric Functions" },
  { class: 11, subject: "Mathematics", topic: "Complex Numbers" },
  { class: 11, subject: "Mathematics", topic: "Permutations and Combinations" },
  { class: 11, subject: "Mathematics", topic: "Binomial Theorem" },
  { class: 11, subject: "Mathematics", topic: "Conic Sections" },
  { class: 11, subject: "Mathematics", topic: "Limits and Derivatives" },
  { class: 12, subject: "Physics", topic: "Electrostatics" },
  { class: 12, subject: "Physics", topic: "Current Electricity" },
  { class: 12, subject: "Physics", topic: "Optics" },
  {
    class: 12,
    subject: "Physics",
    topic: "Magnetic Effects of Current and Magnetism",
  },
  {
    class: 12,
    subject: "Physics",
    topic: "Electromagnetic Induction and Alternating Currents",
  },
  { class: 12, subject: "Chemistry", topic: "Solutions" },
  { class: 12, subject: "Chemistry", topic: "Electrochemistry" },
  { class: 12, subject: "Chemistry", topic: "Chemical Kinetics" },
  { class: 12, subject: "Chemistry", topic: "Coordination Compounds" },
  { class: 12, subject: "Chemistry", topic: "Haloalkanes and Haloarenes" },
  { class: 12, subject: "Chemistry", topic: "Alcohols, Phenols, and Ethers" },
  {
    class: 12,
    subject: "Chemistry",
    topic: "Aldehydes, Ketones, and Carboxylic Acids",
  },
  { class: 12, subject: "Chemistry", topic: "Biomolecules" },
  { class: 12, subject: "Mathematics", topic: "Relations and Functions" },
  {
    class: 12,
    subject: "Mathematics",
    topic: "Inverse Trigonometric Functions",
  },
  {
    class: 12,
    subject: "Mathematics",
    topic: "Continuity and Differentiability",
  },
  { class: 12, subject: "Mathematics", topic: "Integrals" },
  { class: 12, subject: "Mathematics", topic: "Differential Equations" },
  { class: 12, subject: "Mathematics", topic: "Three-Dimensional Geometry" },
];
